name: Deploy a AWS

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install and Build Lambda
        run: |
          cd lambdas/hola-tu
          npm install
          npm run build

      - name: CDK Bootstrap
        run: |
          cd lambdas/hola-tu/dist
          npx cdk bootstrap

      - name: CDK Deploy
        run: |
          cd lambdas/hola-tu/dist
          npx cdk deploy --require-approval never