name: Deploy a AWS

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build Lambda Logic
        # Primero compilamos la función en su carpeta original
        working-directory: ./lambdas/hola-tu
        run: |
          npm install
          npm run build

      - name: Install CDK and Deploy
        # Ahora entramos a la carpeta que GitHub espera
        working-directory: ./cdk/lambda
        run: |
          npm install
          npx cdk bootstrap
          npx cdk deploy --require-approval never